version: "3.8"
services:
  database:
    build: ./Database
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: insurance_db
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  db_data:
